export const INIT_COORDS = '@slite/react-dnd-core/INIT_COORDS'
export const BEGIN_DRAG = '@slite/react-dnd-core/BEGIN_DRAG'
export const PUBLISH_DRAG_SOURCE = '@slite/react-dnd-core/PUBLISH_DRAG_SOURCE'
export const HOVER = '@slite/react-dnd-core/HOVER'
export const DROP = '@slite/react-dnd-core/DROP'
export const END_DRAG = '@slite/react-dnd-core/END_DRAG'
